import{i as l,S as m}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const c="/goit-js-hw-11-2/assets/bi_x-octagon-ddf7add7.svg",n={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function u(){n.loader.classList.toggle("hidden")}n.form.addEventListener("submit",d);function g(o){const t=new URLSearchParams({key:"42272856-fbb9ecaa9aa7f62044da3b204",image_type:"photo",orientation:"horizontal",safesearch:"true",q:o}),s="https://pixabay.com/api/",i=`?${t}`,e=s+i;return fetch(e).then(r=>{if(r.ok)return r.json();throw new Error(r.status)})}function d(o){o.preventDefault(),u();const t=o.target.elements.query.value;g(t).then(s=>{if(u(),t===""){l.warning({message:"Sorry, you forgot to enter a search term. Please try again!",position:"topRight",messageSize:"16px",timeout:2e3});return}else parseInt(s.totalHits)>0?y(s.hits):(n.gallery.innerHTML="",l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:c,color:"white",timeout:2e3}))}).catch(s=>{l.error({message:"Error",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:c,color:"white",timeout:2e3})}),o.target.reset()}function p({largeImageURL:o,webformatURL:t,tags:s,likes:i,views:e,comments:r,downloads:a}){return`<a class="gallery-link" href="${o}"><img class="gallery-image" src="${t}" alt="${s}"/>
  <div class="gallery-review">
  <div class="gallery-review-item"><b>Likes</b> <span>${i}</span></div>
  <div class="gallery-review-item"><b>Views</b> <span>${e}</span></div>
  <div class="gallery-review-item"><b>Comments</b> <span>${r}</span></div>
  <div class="gallery-review-item"><b>Downloads</b> <span>${a}</span></div>
  </div></a>
    `}let f=new m(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function y(o){const t=o.map(p).join("");n.gallery.innerHTML=t,f.refresh()}
//# sourceMappingURL=commonHelpers.js.map
